// Mock data for demo mode
export const mockProducts = [
  {
    id: '1',
    slug: 'premium-dog-food',
    name: 'Premium Dog Food',
    description: '<p>High-quality nutrition for your furry friend. Made with real chicken and vegetables.</p>',
    price: 49.99,
    originalPrice: 59.99,
    image: 'https://placehold.co/400x400/e2e8f0/475569?text=Dog+Food',
    images: [
      { url: 'https://placehold.co/400x400/e2e8f0/475569?text=Dog+Food', alt: 'Premium Dog Food' },
      { url: 'https://placehold.co/400x400/e2e8f0/475569?text=Dog+Food+2', alt: 'Premium Dog Food angle 2' },
    ],
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    isOnSale: true,
    brand: 'PetNutrition Pro',
    sku: 'DF-001',
    category: { id: '1', name: 'Dog Food', slug: 'dog-food' },
  },
  {
    id: '2',
    slug: 'cat-scratching-post',
    name: 'Cat Scratching Post Deluxe',
    description: '<p>Multi-level scratching post with cozy hideaway spots for your cat.</p>',
    price: 79.99,
    originalPrice: null,
    image: 'https://placehold.co/400x400/fef3c7/92400e?text=Cat+Post',
    images: [
      { url: 'https://placehold.co/400x400/fef3c7/92400e?text=Cat+Post', alt: 'Cat Scratching Post' },
    ],
    rating: 4.8,
    reviewCount: 256,
    inStock: true,
    isOnSale: false,
    brand: 'FelineFun',
    sku: 'CS-002',
    category: { id: '2', name: 'Cat Furniture', slug: 'cat-furniture' },
  },
  {
    id: '3',
    slug: 'dog-leash-premium',
    name: 'Premium Retractable Dog Leash',
    description: '<p>Durable retractable leash with comfortable grip handle. Extends up to 16 feet.</p>',
    price: 24.99,
    originalPrice: 34.99,
    image: 'https://placehold.co/400x400/dbeafe/1e40af?text=Dog+Leash',
    images: [
      { url: 'https://placehold.co/400x400/dbeafe/1e40af?text=Dog+Leash', alt: 'Dog Leash' },
    ],
    rating: 4.3,
    reviewCount: 89,
    inStock: true,
    isOnSale: true,
    brand: 'WalkRight',
    sku: 'DL-003',
    category: { id: '3', name: 'Dog Accessories', slug: 'dog-accessories' },
  },
  {
    id: '4',
    slug: 'interactive-cat-toy',
    name: 'Interactive Laser Cat Toy',
    description: '<p>Automatic laser toy that keeps your cat entertained for hours.</p>',
    price: 19.99,
    originalPrice: null,
    image: 'https://placehold.co/400x400/fce7f3/9d174d?text=Cat+Toy',
    images: [
      { url: 'https://placehold.co/400x400/fce7f3/9d174d?text=Cat+Toy', alt: 'Cat Toy' },
    ],
    rating: 4.6,
    reviewCount: 312,
    inStock: true,
    isOnSale: false,
    brand: 'PlayPaws',
    sku: 'CT-004',
    category: { id: '4', name: 'Cat Toys', slug: 'cat-toys' },
  },
  {
    id: '5',
    slug: 'orthopedic-dog-bed',
    name: 'Orthopedic Memory Foam Dog Bed',
    description: '<p>Supportive memory foam bed perfect for senior dogs or dogs with joint issues.</p>',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://placehold.co/400x400/d1fae5/065f46?text=Dog+Bed',
    images: [
      { url: 'https://placehold.co/400x400/d1fae5/065f46?text=Dog+Bed', alt: 'Dog Bed' },
    ],
    rating: 4.9,
    reviewCount: 445,
    inStock: true,
    isOnSale: true,
    brand: 'ComfyPet',
    sku: 'DB-005',
    category: { id: '5', name: 'Dog Beds', slug: 'dog-beds' },
  },
  {
    id: '6',
    slug: 'fish-aquarium-kit',
    name: 'Complete Aquarium Starter Kit',
    description: '<p>Everything you need to start your first aquarium. Includes tank, filter, and LED lighting.</p>',
    price: 129.99,
    originalPrice: null,
    image: 'https://placehold.co/400x400/cffafe/0e7490?text=Aquarium',
    images: [
      { url: 'https://placehold.co/400x400/cffafe/0e7490?text=Aquarium', alt: 'Aquarium Kit' },
    ],
    rating: 4.4,
    reviewCount: 67,
    inStock: true,
    isOnSale: false,
    brand: 'AquaLife',
    sku: 'AQ-006',
    category: { id: '6', name: 'Fish Supplies', slug: 'fish-supplies' },
  },
];

export const mockCategories = [
  { id: '1', name: 'Dog Food', slug: 'dog-food', image: 'https://placehold.co/200x200/e2e8f0/475569?text=Dog+Food', productCount: 45 },
  { id: '2', name: 'Cat Furniture', slug: 'cat-furniture', image: 'https://placehold.co/200x200/fef3c7/92400e?text=Cat+Furniture', productCount: 32 },
  { id: '3', name: 'Dog Accessories', slug: 'dog-accessories', image: 'https://placehold.co/200x200/dbeafe/1e40af?text=Dog+Accessories', productCount: 78 },
  { id: '4', name: 'Cat Toys', slug: 'cat-toys', image: 'https://placehold.co/200x200/fce7f3/9d174d?text=Cat+Toys', productCount: 56 },
  { id: '5', name: 'Dog Beds', slug: 'dog-beds', image: 'https://placehold.co/200x200/d1fae5/065f46?text=Dog+Beds', productCount: 23 },
  { id: '6', name: 'Fish Supplies', slug: 'fish-supplies', image: 'https://placehold.co/200x200/cffafe/0e7490?text=Fish+Supplies', productCount: 41 },
];

export const mockUser = {
  id: 'user-1',
  email: 'demo@ironpets.com',
  firstName: 'Demo',
  lastName: 'User',
  phone: '555-123-4567',
  createdAt: new Date().toISOString(),
};

export const mockOrders = [
  {
    id: 'order-1',
    orderNumber: 'IP-2024-001',
    status: 'delivered',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    total: 124.97,
    items: [
      { id: '1', product: mockProducts[0], quantity: 2 },
      { id: '2', product: mockProducts[2], quantity: 1 },
    ],
  },
  {
    id: 'order-2',
    orderNumber: 'IP-2024-002',
    status: 'shipped',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    total: 79.99,
    items: [
      { id: '3', product: mockProducts[1], quantity: 1 },
    ],
  },
];

export const mockPets = [
  {
    id: 'pet-1',
    name: 'Buddy',
    species: 'dog',
    breed: 'Golden Retriever',
    age: 3,
    weight: 65,
    image: 'https://placehold.co/200x200/fef3c7/92400e?text=Buddy',
  },
  {
    id: 'pet-2',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Maine Coon',
    age: 5,
    weight: 15,
    image: 'https://placehold.co/200x200/e0e7ff/4338ca?text=Whiskers',
  },
];
